language: perl6

os:
  - linux
  - osx

perl6:
  - latest

install:
  - rakudobrew build-zef
  - zef install --deps-only --test-depends --/test .
  - zef install App::Prove6 --/test
  - rakudobrew rehash

script: prove6 -v -l t
sudo: false
